### ISSUE TITLE
关于华硕B85MG开4g空间

### ISSUE THREAD

**Issue by pumpkin-nbc** [azhuge233/UbisoftGiveawayNotifier#12]
大佬 我从你博客过来的 想问下关于这个主板  他手动修改bios也不支持吗

**Comment by azhuge233** [comment]
我当时没有修改成功，一方面是因为时间紧又比较复杂，折腾不动，另一方面是当时这个新买的b85还在退货时间内，我担心还有别的坑直接换主板了

b85平台实在太旧，发行的时间“4G以上解码”的标准应该都还没有提出(这个没去考证，不确定)，修改BIOS的前提是主板硬件支持

我记得当时还搜到了一个b85用P40的贴吧帖子，出现的问题一模一样，那个楼主最后换成X99就没问题了

> 另：问题尽量在博客讨论，issue不适合做无关问答
